services:
  vault:
    build:
      context: ./vault
      dockerfile: vault.dockerfile
    ports:
      - "80:8001"
    volumes:
      - ./vault/vault:/home/vault/vault
    image: vault:latest

  p3vaildev:
    build:
      context: ./p3vaildev
      dockerfile: p3vaildev.dockerfile
    ports:
      - "8080:8001"
    volumes:
      - ./p3vaildev/data:/home/p3vaildev/data
      - ./p3vaildev/p3vaildev:/home/p3vaildev/p3vaildev
    image: p3vaildev:latest
