[project]
name = "vault"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "Flask>=2.3.2",
    "gunicorn>=21.2.0",
    "flask-sqlalchemy>=3.0.5"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
